// The installable-web-app layer: manifest, icons and service worker, after aether-and-brass/tools/pwa.js.
//
// Installed, the arcade is one app on the home screen that opens onto the shelf, holds landscape, and plays every
// game with no network at all: the worker precaches the shelf, each game's single page and each cover. None of it
// is committed - tools/build.js writes it beside dist/index.html, and tools/server.js serves the dev worker.
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { renderIcon } from './icon.js';

/** Icons the manifest advertises. 180 is Apple's home-screen size; 192/512 are Android's. */
export const ICONS = [
  { path: 'icons/icon-32.png', size: 32, purpose: 'any' },
  { path: 'icons/icon-180.png', size: 180, purpose: 'any' },
  { path: 'icons/icon-192.png', size: 192, purpose: 'any' },
  { path: 'icons/icon-512.png', size: 512, purpose: 'any' },
  { path: 'icons/icon-maskable-512.png', size: 512, purpose: 'maskable' },
];
export const MANIFEST_PATH = 'manifest.webmanifest';
export const SW_PATH = 'sw.js';
/** Every cache this worker makes starts with this, and it only ever deletes its own. */
const CACHE_PREFIX = 'arcade-';

/**
 * The manifest. Every URL is relative: the site is published under a project path (/arcade/), so an absolute "/"
 * would scope the app to the wrong place.
 */
export function manifestJson(games) {
  const titles = games.map((g) => g.title);
  const named = titles.length > 1 ? titles.slice(0, -1).join(', ') + ' and ' + titles[titles.length - 1] : titles.join('');
  return JSON.stringify({
    name: 'The Making Game Arcade',
    short_name: 'The Making Game Arcade',
    description: `${named}, on one shelf. Drawn and synthesized in code, and playable with no network once installed.`,
    id: './',
    start_url: './',
    scope: './',
    // Fullscreen where the platform allows it (Android), plain standalone where it does not (iOS).
    display: 'fullscreen',
    display_override: ['fullscreen', 'standalone'],
    // Every game on the shelf is a 640x360 landscape picture.
    orientation: 'landscape',
    background_color: '#14101a',
    theme_color: '#14101a',
    // An invite (#<game>?room=CODE) is a link into this scope: an installed copy should be what opens it, in the
    // window already open. Honoured where supported (Android); elsewhere the room code still carries a guest in.
    launch_handler: { client_mode: 'navigate-existing' },
    handle_links: 'preferred',
    categories: ['games', 'entertainment'],
    icons: ICONS.map((i) => ({ src: i.path, sizes: `${i.size}x${i.size}`, type: 'image/png', purpose: i.purpose })),
  }, null, 2) + '\n';
}

/** Everything the worker precaches, given what the build produced: a cover is there only if it was captured. */
export function precacheList(dist, games) {
  const list = ['./index.html', './' + MANIFEST_PATH, ...ICONS.map((i) => './' + i.path)];
  for (const g of games) {
    list.push(`./games/${g.id}/index.html`);
    if (fs.existsSync(path.join(dist, 'games', g.id, 'cover.png'))) list.push(`./games/${g.id}/cover.png`);
  }
  return list;
}

/**
 * The service worker. `version` names the cache, so a new build installs into a fresh one and activating it
 * deletes the older ones - only ever ours: every game on this site shares the origin's Cache Storage.
 */
export function swSource(version, precache) {
  return `// Generated by tools/pwa.js - do not edit; edit that file.
// Cache-first over one fixed list, as each game's own worker is: the shelf and every game are single pages, so an
// installed arcade needs nothing else and opens instantly, offline. Updates ride the worker - the browser re-fetches
// this script, a new build changes VERSION, and installing fills a fresh cache and drops the old one.
const VERSION = ${JSON.stringify(version)};
const CACHE = ${JSON.stringify(CACHE_PREFIX)} + VERSION;
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    // Ours only: the games' own workers on this origin keep caches beside these.
    for (const key of await caches.keys()) if (key.startsWith(${JSON.stringify(CACHE_PREFIX)}) && key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const root = new URL('./', self.registration.scope).pathname;
  // Our own scope only. The games' signalling broker and their peers are somebody else's, and not HTTP at all.
  if (url.origin !== self.location.origin || !url.pathname.startsWith(root)) return;
  const rel = url.pathname.slice(root.length);
  // A navigation is a page: inside games/<id>/ it is that game (the shelf frames it there), anywhere else the shelf.
  const game = /^games\\/([a-z0-9-]+)\\//.exec(rel);
  const key = req.mode === 'navigate' ? (game ? './games/' + game[1] + '/index.html' : './index.html') : './' + rel;
  if (PRECACHE.indexOf(key) === -1) return; // not something we hold: straight to the network
  e.respondWith(caches.open(CACHE).then((c) => c.match(key).then((hit) => hit || fetch(req).then((res) => {
    // Missing from a cache we filled at install: something cleared it. Take it back while we are online.
    if (res.ok && !res.redirected) c.put(key, res.clone());
    return res;
  }))));
});
`;
}

/**
 * The dev worker: registers, has a fetch handler (so install prompts behave), caches nothing, and clears any cache
 * a production build of the arcade left on localhost.
 */
export const DEV_SW = `// Dev worker (tools/pwa.js DEV_SW): never caches, so a reload always shows what is on disk.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) if (key.startsWith(${JSON.stringify(CACHE_PREFIX)})) await caches.delete(key);
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', () => { /* straight to the network */ });
`;

/**
 * Every generated file, as path (relative to dist/) -> bytes. Run after the shelf, the games and the covers are in
 * dist/: the worker's version is a hash of everything it precaches, so any change to any of it renames the cache.
 */
export function pwaAssets(dist, games) {
  const files = new Map();
  for (const icon of ICONS) files.set(icon.path, renderIcon(icon.size, { maskable: icon.purpose === 'maskable' }));
  files.set(MANIFEST_PATH, Buffer.from(manifestJson(games), 'utf8'));
  const precache = precacheList(dist, games);
  const hash = crypto.createHash('sha256');
  for (const key of precache) {
    const rel = key.slice(2);
    hash.update(rel);
    hash.update(files.has(rel) ? files.get(rel) : fs.readFileSync(path.join(dist, rel)));
  }
  files.set(SW_PATH, Buffer.from(swSource(hash.digest('hex').slice(0, 12), precache), 'utf8'));
  return files;
}
